# Generated by Django 5.2.1 on 2026-01-06 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('shinobi', 'Shinobi'), ('pegasus', 'Pegasus'), ('chimera', 'Chimera'), ('phoenix', 'Phoenix')], max_length=20, unique=True)),
                ('points', models.IntegerField(default=0)),
                ('color', models.CharField(default='#FFFFFF', max_length=7)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
