# Generated by Django 6.0 on 2026-01-06 03:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(choices=[('shinobi', 'Shinobi'), ('pegasus', 'Pegasus'), ('chimera', 'Chimera'), ('phoenix', 'Phoenix')], max_length=20)),
                ('points', models.IntegerField()),
                ('opponent', models.CharField(blank=True, max_length=100, null=True)),
                ('event', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
