# Generated by Django 6.0 on 2026-01-06 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0002_scorelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorelog',
            name='opponent_score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='scorelog',
            name='team_score',
            field=models.IntegerField(default=0),
        ),
    ]
