# Generated by Django 5.2.1 on 2026-01-06 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0003_scorelog_opponent_score_scorelog_team_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorelog',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
