# Generated by Django 6.0 on 2026-01-07 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0004_scorelog_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('major', 'Major'), ('minor', 'Minor'), ('minigame', 'Minigame')], max_length=20)),
                ('type', models.CharField(choices=[('sports', 'Sports'), ('litmus', 'LITMUS'), ('minigame', 'Minigame')], max_length=20)),
                ('points_1st', models.IntegerField()),
                ('points_2nd', models.IntegerField()),
                ('points_3rd', models.IntegerField()),
                ('points_4th', models.IntegerField()),
                ('points_dq', models.IntegerField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['type', 'category', 'name'],
            },
        ),
    ]
