# Generated by Django 5.2.1 on 2026-01-07 02:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0005_game'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(choices=[('shinobi', 'Shinobi'), ('pegasus', 'Pegasus'), ('chimera', 'Chimera'), ('phoenix', 'Phoenix')], max_length=20)),
                ('placement', models.IntegerField(choices=[(1, '1st Place'), (2, '2nd Place'), (3, '3rd Place'), (4, '4th Place'), (5, 'DQ')])),
                ('notes', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='scoring.game')),
            ],
            options={
                'ordering': ['game', 'placement'],
                'unique_together': {('game', 'team')},
            },
        ),
    ]
