# Generated by Django 5.2.1 on 2026-01-08 01:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0006_gameresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_name', models.CharField(max_length=100)),
                ('team', models.CharField(blank=True, choices=[('shinobi', 'Shinobi'), ('pegasus', 'Pegasus'), ('chimera', 'Chimera'), ('phoenix', 'Phoenix')], max_length=20, null=True)),
                ('points', models.IntegerField(default=5)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_awards', to='scoring.game')),
            ],
            options={
                'ordering': ['game', 'award_name'],
                'unique_together': {('game', 'award_name')},
            },
        ),
    ]
