# Generated by Django 6.0 on 2026-01-13 02:43

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0008_contestant'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestant',
            name='overlay_left',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Transparent overlay image for left side', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='contestant',
            name='overlay_right',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Transparent overlay image for right side', max_length=255, null=True, verbose_name='image'),
        ),
    ]
