# Generated by Django 6.0 on 2026-01-13 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0009_contestant_overlay_left_contestant_overlay_right'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contestant',
            name='overlay_left',
        ),
        migrations.RemoveField(
            model_name='contestant',
            name='overlay_right',
        ),
    ]
