# Generated by Django 6.0 on 2026-01-13

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0010_remove_contestant_overlay_left_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestant',
            name='overlay_up',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Transparent overlay image for top', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='contestant',
            name='overlay_down',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Transparent overlay image for bottom', max_length=255, null=True, verbose_name='image'),
        ),
    ]
