# Generated by Django 6.0 on 2026-01-14 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0011_rename_contestant_overlays'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contestant',
            name='overlay_down',
        ),
        migrations.RemoveField(
            model_name='contestant',
            name='overlay_up',
        ),
    ]
